/*
 * Linux x64 Shellcode Decoder Template
 * Generated by ShellcodingDream
 * 
 * Compilation:
 * gcc -fno-stack-protector -z execstack -O0 -o decoder decoder.c
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>

// ===== ENCODED SHELLCODE (WILL BE INSERTED HERE) =====
// SHELLCODE_PLACEHOLDER
// ===== END ENCODED SHELLCODE =====

// ===== DECODER STUB (WILL BE INSERTED HERE) =====
// DECODER_PLACEHOLDER
// ===== END DECODER STUB =====

int main(int argc, char *argv[]) {
    
    // Allocate executable memory
    void *exec_mem = mmap(NULL, shellcode_len, PROT_READ | PROT_WRITE | PROT_EXEC,
                          MAP_ANON | MAP_PRIVATE, -1, 0);
    
    if (exec_mem == MAP_FAILED) {
        perror("mmap");
        return 1;
    }
    
    // Copy shellcode to executable memory
    memcpy(exec_mem, shellcode, shellcode_len);
    
    // Decode in-place
    decode_shellcode();
    
    // Execute
    int (*ret)() = (int(*)())exec_mem;
    ret();
    
    // Cleanup (usually not reached)
    munmap(exec_mem, shellcode_len);
    
    return 0;
}
